[package]
name = "async-stream"
# When releasing to crates.io:
# - Update version number
#   - lib.rs: html_root_url.
#   - README.md
# - Update CHANGELOG.md
# - Update doc URL.
#   - Cargo.toml
#   - README.md
# - Create git tag
version = "0.1.1"
edition = "2018"
license = "MIT"
authors = ["Carl Lerche <me@carllerche.com>"]
description = "Asynchronous streams using async & await notation"
documentation = "https://docs.rs/async-stream/0.1.1/async-stream"
homepage = "https://github.com/tokio-rs/async-stream"
repository = "https://github.com/tokio-rs/async-stream"
readme = "README.md"

[dependencies]
async-stream-impl = { version = "0.1.1", path = "../async-stream-impl" }
futures-core-preview = "=0.3.0-alpha.18"

[dev-dependencies]
tokio = "=0.2.0-alpha.4"
tokio-test = "=0.2.0-alpha.4"
futures-util-preview = "=0.3.0-alpha.18"
trybuild = "1.0"
